title: 'giridharprasath.github.io'
description: ""
baseurl: "/"
url: "https://github.com/GiridharPrasath/GiridharPrasath.github.io"

header_pages:
- index.md
- about.md
- contact.md

style: dark

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
