title: 'giridharprasath.github.io'
description: ""
baseurl: "/"
url: "https://github.com/GiridharPrasath/GiridharPrasath.github.io"

header_pages:
- index.md
- about.md
- contact.md

style: dark

footer: 'giridhar prasath, <a href="https://twitter.com/giridhar_prasat">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag
