baseURL = 'https://z3phyr.github.io'
languageCode = 'en-us'
themesDir = "themes"
theme = 'nightfall'
title = 'z3phyr'

# config.toml

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'doom-one'
        tabWidth = 4

[params]
author = "z3phyr"
user = "z3phyr"
hostname = 'z3phyr.github.io'
footerHtml = '© 2023 <a href="https://twitter.com/z3phyrrrrr" class="footerLink">z3phyr</a>. CC BY 4.0'
customCSS = "css/custom.css"  # Adjust the path based on your project structure

[menu]
  [[menu.header]]
    name = "blog"
    weight = 1
    url = "/post"

  [[menu.header]]
    name = "About"
    weight = 0
    url = "/about"

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/GiridharPrasath"
icon = "fa fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`

[[params.social]]
key = 1
name = "Twitter"
url = "https://twitter.com/z3phyrrrrr"
icon = "fa fa-twitter"  # Add link to your icon font to `layouts/partials/custom-head.html`


[[params.social]]
key = 2
name = "Linkedin"
url = "https://www.linkedin.com/in/giridhar-p-601316b8/"
icon = "fa fa-linkedin"  # Add link to your icon font to `layouts/partials/custom-head.html`

[[params.social]]
key = 3
name = "Email"
url = "mailto:email@giridh1337@gmail.com"
icon = "fa fa-envelope"  # Add link to your icon font to `layouts/partials/custom-head.html`