baseURL = 'https://giridharprasath.github.io'
languageCode = 'en-us'
title = 'Personal blog'
theme = 'nightfall'


[[params.social]]
key = 0
name = "github"
url = "https://github.com/GiridharPrasath"
icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"

[[params.social]]
key = 5
name = "mastodon"
url = "https://www.example.com"
rel = "me"  # You can also add rel to social link

[[params.social]]
key = 3
name = "email"
url = "mailto:email@giridh1337@gmail.com"